# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Glstring(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, glstring: str=None):
        """
        Glstring - a model defined in Swagger

        :param glstring: The glstring of this Glstring.
        :type glstring: str
        """
        self.swagger_types = {
            'glstring': str
        }

        self.attribute_map = {
            'glstring': 'glstring'
        }

        self._glstring = glstring

    @classmethod
    def from_dict(cls, dikt) -> 'Glstring':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Glstring of this Glstring.
        :rtype: Glstring
        """
        return deserialize_model(dikt, cls)

    @property
    def glstring(self) -> str:
        """
        Gets the glstring of this Glstring.

        :return: The glstring of this Glstring.
        :rtype: str
        """
        return self._glstring

    @glstring.setter
    def glstring(self, glstring: str):
        """
        Sets the glstring of this Glstring.

        :param glstring: The glstring of this Glstring.
        :type glstring: str
        """

        self._glstring = glstring

